/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.4/samples
 */
plugins{
	java
}

version="1.0"
group="ru.ac.uniyar.testingcourse"

repositories{
	mavenCentral()
}

dependencies{
	implementation("com.google.guava:guava:33.3.1-jre")
	implementation("org.junit.jupiter:junit-jupiter:5.11.1")
	implementation("org.assertj:assertj-core:3.26.3")
}

tasks.named<Test>("test"){
	useJUnitPlatform()
}


/**
*plugins{
*	id 'java'
*}
*
*version="1.0"
*group="ru.ac.uniyar.testingcourse"
*
*repositories{
*	mavenCentral()
*}
*
*dependencies{
*	implementation platform('org.junit:junit-bom:5.9.1')
*	testImplementation 'org.junit.jupiter:junit-jupiter'
*}
*
*test{
*	useJUnitPlatform()
*}
*
*
*
*
*/
